<?php

return array (
  'version' => '5.4',
  'title' => 'Regions',
  'type' => 'rfc_regions',
  'id' => '5fdbb49d840f9',
  'updated' => 1608245368,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
    ),
    '5fdbb4c6e1ea1' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Navigation Title',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fdbae096391e',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    '5fdbb9e02f9b3' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Hero Title',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fd7da1f0f519',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    '5fdbb9e02f9b7' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Hero Short Text',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fd7da1f0f8df',
      'excerpt_length' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    '5fdbb4c6e1ea7' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Hero Image',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fd7da1f0fcac',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    'date' => 
    array (
      'type' => 'date',
      'label' => 'Date',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);