<?php

return array (
  'version' => '5.4',
  'title' => 'Locations',
  'type' => 'rfc_locations',
  'id' => '5fdb90a756a47',
  'updated' => 1608600862,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
    ),
    '5fdb90ee2855a' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Navigation Title',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fdbaf1c2e28e',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    '5fdbb94d663c8' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Hero Title',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5f627060127ca',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    '5fdbb94d663cd' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Hero Short Text',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5f6270ea127cc',
      'excerpt_length' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    '5fdbb435d64e6' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Hero Image',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5f63c308d92b9',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    '5fe14d1ed1391' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Is Country',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fe14ca2978ef',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    '5fe14b55ce715' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Category Image',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fe14a88364ff',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    '5fdb90ee28556' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Destination',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fd7ac2ebb604',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    '5fe12435a1c22' => 
    array (
      'type' => 'column-author_name',
      'label' => 'Author',
      'width' => '',
      'width_unit' => '%',
      'display_author_as' => 'display_name',
      'user_link_to' => 'edit_user',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    'date' => 
    array (
      'type' => 'date',
      'label' => 'Date',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);