<?php

return array (
  'version' => '5.4',
  'title' => 'Destinations',
  'type' => 'rfc_destinations',
  'id' => '5fdbb28b974a8',
  'updated' => 1611776187,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
    ),
    '5fdbb2c07cd75' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Navigation Title',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fdbaeda25a3a',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    '5fdbb2c07cd7a' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Region',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fc53363628e2',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    '5fea3ae22edd2' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Locations',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fea3a88df109',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    '5fe12a9d773a9' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Activities',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fe125b203346',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    '5fdbe00b3c529' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Is Country',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fdbdeec81832',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    '60104960a82c1' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Is Bucket List',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_60104914eb05b',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    '6011c0bb62e39' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Default Search Link',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fdbaf61814b6',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    '5fe1247f20602' => 
    array (
      'type' => 'column-author_name',
      'label' => 'Author',
      'width' => '',
      'width_unit' => '%',
      'display_author_as' => 'display_name',
      'user_link_to' => 'edit_user',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    'date' => 
    array (
      'type' => 'date',
      'label' => 'Date',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);