<?php

return array (
  'version' => '5.4',
  'title' => 'Travel Guides',
  'type' => 'rfc_travel_guides',
  'id' => '5feced60af61d',
  'updated' => 1610138535,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
    ),
    '5feced9f16588' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Destination',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5feb79f98e2ac',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    '5ff8c3a786683' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Categories',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5ff8c322b2dd0',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    '5feced9f1658c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Featured Image',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5feb942a2e7b1',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    '5feced9f1658e' => 
    array (
      'type' => 'column-author_name',
      'label' => 'Author',
      'width' => '',
      'width_unit' => '%',
      'display_author_as' => 'display_name',
      'user_link_to' => 'edit_user',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
    ),
    'date' => 
    array (
      'type' => 'date',
      'label' => 'Date',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);