<?php

return array (
  'version' => '5.5.3',
  'title' => 'Deals',
  'type' => 'rfc_deals',
  'id' => '61dca42e9152d',
  'updated' => 1642117551,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '61dca3f7b374bc' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Navigation Title',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_61dc9f9d53590',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '61dca3f7b374bc',
    ),
    '61dca7841d70a4' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Description',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_61dca7348a395',
      'excerpt_length' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'editable_type' => 'textarea',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '61dca7841d70a4',
    ),
    '61e07c39ced918' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Applicable To',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_61e05f01ebdd5',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '61e07c39ced918',
    ),
    '61e07c5396c8b4' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'SERP Link',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_61e05fceebdd7',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '61e07c5396c8b4',
    ),
    '61dca4264d9168' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Products',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_61dca01434c1a',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '61dca4264d9168',
    ),
    '61dca4107851ec' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Regions',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_61dc9f9d62140',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '61dca4107851ec',
    ),
    '61dca41eb4fdf4' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Destinations',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_61dc9f9d65c9a',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '61dca41eb4fdf4',
    ),
    '61dca50672b020' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Categories',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_61dc9f9d6d5d7',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '61dca50672b020',
    ),
    '61dca405c8f5c4' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Featured Image',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_61dc9f9d56faa',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '61dca405c8f5c4',
    ),
    '61dca3e7d020c4' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Is Exclusive',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_61dca09f34c1b',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '61dca3e7d020c4',
    ),
    '61dcab3f9020c4' => 
    array (
      'type' => 'column-postid',
      'label' => 'ID',
      'width' => '',
      'width_unit' => '%',
      'before' => '',
      'after' => '',
      'export' => 'off',
      'sort' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '61dcab3f9020c4',
    ),
    'date' => 
    array (
      'type' => 'date',
      'label' => 'Date',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
      'name' => 'date',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);