<?php

return array (
  'version' => '5.6.4',
  'title' => 'Authors',
  'type' => 'rfc_authors',
  'id' => '68cd8bff1a0e3',
  'updated' => 1758301183,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '68cd8bb05d70a4' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Image',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_68cd8b275d23d',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '68cd8bb05d70a4',
    ),
    '68cd8bd24b020c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Description',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_68cd8b315d23e',
      'excerpt_length' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'editable_type' => 'textarea',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '68cd8bd24b020c',
    ),
    '68cd8be3b47ae0' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Twitter',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_68cd8b565d240',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '68cd8be3b47ae0',
    ),
    '68cd8befba1cac' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Website',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_68cd8b4a5d23f',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '68cd8befba1cac',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);